using UnityEngine;
using System.Collections.Generic;
using SimpleFileBrowser;
using System.Linq;
using System.IO;
using System;

namespace spz {

	// Similar to Art_IconsUI_List, but this one is a list for 2D Background images.
	// Shows a collection of rectangles (icons) each referencing a texture of its Generation.
	// Used for previewing the images generated by stable diffusion server.
	public class ArtBG_IconsUI_List : IconsUI_List{
	    public static ArtBG_IconsUI_List instance { get; private set; } = null;

	    [SerializeField] IconUI _icons_PREFAB;


	    public override IconUI _mainSelectedIcon { 
	        get => 
	            isPretendNoBackground? null : base._mainSelectedIcon; 
	        protected set 
	            => base._mainSelectedIcon = value; 
	    }


	    bool _isPretendNoBackground = false;
	    public bool isPretendNoBackground => _isPretendNoBackground;
	    public void Set_IsPretendNoBackground(bool isPretend){
	        _isPretendNoBackground = isPretend;
	        if(base._mainSelectedIcon != null){
	            if(isPretend){ base._mainSelectedIcon.preventShowingFrame(requestor:this); }
	            else{ base._mainSelectedIcon.isAllowShowingFrame(originalRequestor:this); }
	        }
	    }

	    public bool hasBackground(bool considerGradientColors){

	        bool hasGradientColors = SkyboxBackground_MGR.instance.isGradientColorClear==false;
	        if(considerGradientColors && hasGradientColors){ return true; }

	        return base._mainSelectedIcon!=null && !_isPretendNoBackground;
	    }


	    //When we begin generation and will need to display the progress of images generation.
	    protected override bool OnWillGenerate_isMyKind( GenData2D genData, out IconUI prefab_ ){
	        prefab_ = null;
	        bool relevantToMe  =  genData.kind==GenerationData_Kind.SD_Backgrounds;
	             relevantToMe |=  genData.kind==GenerationData_Kind.BgNormals_FromFile;
	        if(!relevantToMe){ return false; }

	        prefab_ = _icons_PREFAB;
	        //checking, to avoid changing the value which we could have loaded:
	        if (Save_MGR.instance._isLoading == false){  Set_IsPretendNoBackground(false); }
	        return true;
	    }

	    protected override void onIconUI_Selected(IconUI icon, GenerationData_Kind kind){
	        bool relevantToMe =  kind == GenerationData_Kind.SD_Backgrounds;
	        if(!relevantToMe){ return;}
	        base._mainSelectedIcon = icon;
	        //checking, to avoid changing the value which we could have loaded:
	        if(Save_MGR.instance._isLoading == false){  Set_IsPretendNoBackground(false); }
	    }

	    protected override void OnCustomImageImported_maybeChangeKind(ref GenerationData_Kind kind){
	        if(kind == GenerationData_Kind.UvTextures_FromFile){ 
	            kind = GenerationData_Kind.SD_Backgrounds;
	        }else if(kind == GenerationData_Kind.UvNormals_FromFile){ 
	            kind = GenerationData_Kind.BgNormals_FromFile;
	        }
	    }


	    void On_import_BG_from_currView(){
	        Screenshot_MGR.instance.ScreenshotViewport_viaScript(Vector2.zero, Vector2.one, OnHaveScreenshot);
        
	        void OnHaveScreenshot( Vector2 min_px,  Vector2 max_px, 
	                               Texture2D textureTakeOwnership ){
	            var textures_withoutOwner = new Dictionary<Texture2D, UDIM_Sector>()
	            {
	                { textureTakeOwnership, new UDIM_Sector(0,0) },
	            };
	            base.OnImportCustomImage_OK(GenerationData_Kind.SD_Backgrounds, textures_withoutOwner);
	        }//end()
	    }


	    void On_will_import_3d_model(ModelsHandler_ImporingInfo info){
	        if (info.isKeep_ArtBG_Icons){ return; }
	        /*we actually don't destroy the backgrounds when importing 3d. 
	          Keep the method in case we decide to change that */
	    }


	    public void OnExportAllIcons_Button(){
	        ConfirmPopup_UI.instance.Show("Dump all Art BG images into a folder?\nThis might take some time\n<b>Can overwrite existing files!</b>", onYes, null);
	        void onYes(){
            
	            FileBrowser.ShowLoadDialog( (paths) => {
                
	                string folderPath = paths[0];
	                List<IconUI> icons = base.allMyIcons();
                
	                List<Texture2D> textures = new List<Texture2D>();
	                List<Texture2D> toBeDestroyed = new List<Texture2D>();
	                try {
	                    foreach(IconUI i in icons){
	                        Dictionary<Texture2D,UDIM_Sector> texs = i._genData.GetTextures2D_expensive(out bool destroyWhenDone);
	                        List<Texture2D> keys = texs.Keys.ToList();

	                        textures.AddRange(keys);
	                        if(destroyWhenDone){ toBeDestroyed.AddRange(keys); }
	                    }

	                    for(int i=0; i<textures.Count; ++i){
	                        string tex_path = Path.Combine(folderPath, $"tex_{i}.png");
	                        TextureTools_SPZ.EncodeAndSaveTexture(textures[i], tex_path);
	                    }
	                    Viewport_StatusText.instance.ShowStatusText("Exported all Art BG images", false, 4, false);
	                }
	                catch(Exception e){
	                    Viewport_StatusText.instance.ShowStatusText("Failed to export some Art BG images", false, 4, false);
	                }
	                finally { 
	                    //cleanup
	                    foreach (Texture2D tex in toBeDestroyed){ DestroyImmediate(tex); }
	                }

	            },
	            null, // Cancel callback
	            FileBrowser.PickMode.Folders, false, null, null, "Select a folder", "Select");

	        }//end onYes()
	    }

	    public override void Save( StableProjectorz_SL spz ){
	        spz.artBG_iconList = new ArtBG_IconsList_SL();
	        spz.artBG_iconList.header = new ArtBG_IconsList_Header_SL();
	        _header.Save(spz.artBG_iconList.header);
	        base.OnSaveCommonStuff(spz.artBG_iconList);
	        spz.artBG_iconList.isPretendNoBackground = _isPretendNoBackground;
	        // After base is saved, ensure we store the guid of BASE CLASS's icon
	        // That's because our own overload might pretend that there is no icon:
	        spz.artBG_iconList._mainSelectedIcon_groupGuid = base._mainSelectedIcon?.generation_guid.ToString() ?? "";
	    }

	    public override void Load( StableProjectorz_SL spz ){
	        _header.Load( spz.artBG_iconList.header );
	        base.OnLoadCommonStuff( spz.artBG_iconList );
	        _isPretendNoBackground = spz.artBG_iconList.isPretendNoBackground;
	    }

	    protected override void Awake(){
	        if(instance != null){ DestroyImmediate(this); return; }
	        instance = this;
	        base.Awake();
	        ModelsHandler_3D.Act_onWillLoadModel += On_will_import_3d_model;
	        ExportSave_UI_MGR.OnExportAllArtBG_Icons_Button += OnExportAllIcons_Button;

	        _header.onImport_BG_fromCurrView += On_import_BG_from_currView;
	    }

	    protected override void OnDestroy(){
	        ModelsHandler_3D.Act_onWillLoadModel -= On_will_import_3d_model;
	        base.OnDestroy();
	    }
	}
}//end namespace
